In [2]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[-0.2066269 ,  2.64945214, -0.40072275],
       [ 1.38360772,  1.53972009, -1.27657953]])

In [9]:
data * 10

array([[-9.7835,  4.1602, -7.5556],
       [19.0505,  2.2871, -4.5415]])

In [10]:
data + data

array([[-1.9567,  0.832 , -1.5111],
       [ 3.8101,  0.4574, -0.9083]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [3]:
data1 = [[1, 2, 3], [2, 4, 6]]
arr1 = np.array(data1)
arr1.ndim

2

In [19]:
arr2 = np.identity(3)
arr2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
arr3 = np.full_like(arr2, 3, dtype=np.int32)
arr3

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [33]:
arr4 = np.array(['U10'])
arr4

array(['U10'], dtype='<U3')

In [36]:
arr4 = arr3.astype('f8')
arr4

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [38]:
arr5 = np.random.randn(2, 3)
arr6 = 1 / arr5
arr6 < arr5

array([[False, False, False],
       [ True,  True, False]])

In [47]:
arr0 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])
arr7 = arr0[0]
arr7

array([1, 2, 3])

In [49]:
arr7[:] = 0
arr0

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr8 = arr0[1:3, :2].copy()
arr8

array([[4, 5],
       [7, 8]])

In [17]:
import numpy as np
names = np.array(['A', 'B', 'A', 'C'])
data = np.eye(4, dtype='i4')
names == 'A'

array([ True, False,  True, False])

In [5]:
data[names == 'A']

array([[1, 0, 0, 0],
       [0, 0, 1, 0]])

In [6]:
data[names == 'A', :2]

array([[1, 0],
       [0, 0]])

In [12]:
data[~((names == 'A') | (names == 'C')), 1:]

array([[1, 0, 0]])

In [18]:
data[data > 0] = -1
data

array([[-1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

In [19]:
data[names != 'A'] = 1
data

array([[-1,  0,  0,  0],
       [ 1,  1,  1,  1],
       [ 0,  0, -1,  0],
       [ 1,  1,  1,  1]])

In [24]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr[[4, 3, -1]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [27]:
arr = np.arange(20).reshape(5, 4) + 1
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [28]:
arr[[1, 2, -1], [3, 0, -1]]

array([ 8,  9, 20])

In [31]:
arr[[1, 2]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr[[1, 2]][:, [1, 0]]

array([[ 6,  5],
       [10,  9]])

In [52]:
arr = np.arange(24).reshape((2, 4, 3)) +1
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [53]:
arr.T

array([[[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]],

       [[ 3, 15],
        [ 6, 18],
        [ 9, 21],
        [12, 24]]])

In [54]:
arr.transpose((1, 0, 2))

array([[[ 1,  2,  3],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [19, 20, 21]],

       [[10, 11, 12],
        [22, 23, 24]]])

In [55]:
arr.swapaxes(0, 1)

array([[[ 1,  2,  3],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [19, 20, 21]],

       [[10, 11, 12],
        [22, 23, 24]]])