In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
obj = pd.Series([2, 4, -1, 0])
obj

0    2
1    4
2   -1
3    0
dtype: int64

In [3]:
obj.values

array([ 2,  4, -1,  0], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([2, 4, -1, 0], index=['a', 'c', 'b', 'd'])
obj2

a    2
c    4
b   -1
d    0
dtype: int64

In [6]:
obj2['b']

-1

In [7]:
obj2['c'] = 5
obj2[['a', 'b', 'c']]

a    2
b   -1
c    5
dtype: int64

In [8]:
obj2[obj2 > 0]

a    2
c    5
dtype: int64

In [9]:
obj2 * 2

a     4
c    10
b    -2
d     0
dtype: int64

In [10]:
np.exp(obj2)

a      7.389056
c    148.413159
b      0.367879
d      1.000000
dtype: float64

In [11]:
'b' in obj2

True

In [12]:
sdata = {'A':86, 'B':54, 'XXX':98}
obj3 = pd.Series(sdata)
obj3

A      86
B      54
XXX    98
dtype: int64

In [13]:
names = ['XXX', 'A', 'C']
obj4 = pd.Series(sdata, index=names)
obj4

XXX    98.0
A      86.0
C       NaN
dtype: float64

In [25]:
pd.isnull(obj4)

XXX    False
A      False
C       True
dtype: bool

In [26]:
obj3 + obj4

A      172.0
B        NaN
C        NaN
XXX    196.0
dtype: float64

In [28]:
obj4.name = 'Score'
obj4.index.name = 'name'
obj4

name
XXX    98.0
A      86.0
C       NaN
Name: Score, dtype: float64

In [30]:
obj4.index = [1, 2, 3]
obj4

1    98.0
2    86.0
3     NaN
Name: Score, dtype: float64

In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [4]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [5]:
frame2 = pd.DataFrame(data, 
                      columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [6]:
type(frame2.year)

pandas.core.series.Series

In [7]:
frame2['pop']

one      1.5
two      1.7
three    3.6
four     2.4
five     2.9
six      3.2
Name: pop, dtype: float64

In [10]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [13]:
frame2['debt'] = 1
frame2

year   state  pop  debt
one    2000    Ohio  1.5     1
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     1
four   2001  Nevada  2.4     1
five   2002  Nevada  2.9     1
six    2003  Nevada  3.2     1

In [22]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [23]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [26]:
val = pd.Series([-1, 5, 4], index=['one', 'five', 'three'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5  -1.0
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   4.0
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9   5.0
six    2003  Nevada  3.2   NaN

In [27]:
del frame2['debt']
frame2

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
six    2003  Nevada  3.2

In [29]:
frame2.drop('state', axis=1)

year  pop
one    2000  1.5
two    2001  1.7
three  2002  3.6
four   2001  2.4
five   2002  2.9
six    2003  3.2

In [30]:
frame2.drop('six', inplace=True)
frame2

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [24]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [26]:
pd.DataFrame(pop, index=pd.Series([2001, 2002, 2003]))

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [27]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [29]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [30]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [2]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [4]:
obj

a    0
b    1
c    2
dtype: int64

In [5]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [6]:
type(index)

pandas.core.indexes.base.Index

In [8]:
index[:2]

Index(['a', 'b'], dtype='object')

In [12]:
labels = pd.Index(pd.Series(np.arange(3)))
labels

Int64Index([0, 1, 2], dtype='int64')

In [29]:
obj2 = pd.Series(range(3), index=range(3))
obj2.index

RangeIndex(start=0, stop=3, step=1)

In [30]:
obj2

0    0
1    1
2    2
dtype: int64

In [31]:
obj2.index is labels

False

In [35]:
'b' in obj.index

True

In [38]:
(obj2.index.union(index)).union(index)

Index([0, 1, 2, 'a', 'b', 'c'], dtype='object')

In [39]:
index2 = pd.Index([0, 1, 1, 2, 2])
index2

Int64Index([0, 1, 1, 2, 2], dtype='int64')

In [40]:
obj2.index.union(index2)

Int64Index([0, 1, 1, 2, 2], dtype='int64')

In [41]:
index2.unique()

Int64Index([0, 1, 2], dtype='int64')

In [42]:
index2

Int64Index([0, 1, 1, 2, 2], dtype='int64')

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [15]:
obj = pd.Series([3, 7 ,8 ,9], index=['a', 'b', 'c', 'e'])
obj

a    3
b    7
c    8
e    9
dtype: int64

In [19]:
obj.reindex(['b', 'c', 'd', 'e', 'f'])

b    7.0
c    8.0
d    NaN
e    9.0
f    NaN
dtype: float64

In [17]:
obj.reindex(['b', 'e', 'c', 'd', 'f'], method='ffill')

b    7
e    9
c    8
d    8
f    9
dtype: int64

In [18]:
obj.reindex(['b', 'e', 'c', 'd', 'f'], method='bfill')

b    7.0
e    9.0
c    8.0
d    9.0
f    NaN
dtype: float64

In [20]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [21]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [25]:
states = ['Texas', 'Utah', 'California']
frame1 = frame.reindex(index=['a', 'b', 'c', 'd'], columns=states)
frame1

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [27]:
frame1.reindex(columns=['Texas', 'Utah'])

Texas  Utah
a    1.0   NaN
b    NaN   NaN
c    4.0   NaN
d    7.0   NaN

In [28]:
frame1.index.name = 'letter'
frame1.columns.name = 'states'
frame1

states  Texas  Utah  California
letter                         
a         1.0   NaN         2.0
b         NaN   NaN         NaN
c         4.0   NaN         5.0
d         7.0   NaN         8.0

In [35]:
series1 = Series(np.random.randint(0,150,size=6),
                index=[['a','a','b','b','c','c'],
                       ['期中','期末','期中','期末','期中','期末']])
series1

a  期中    123
   期末      3
b  期中     17
   期末     80
c  期中     88
   期末    108
dtype: int32

In [45]:
frame1 = DataFrame(np.random.randint(0,150,size=(4,6)),
                   index = list('ABCD'),
                   columns=[['python','python','math','math','En','En'],
                            ['期中','期末','期中','期末','期中','期末']])
frame1

python      math        En    
      期中   期末   期中   期末   期中  期末
A     97   15  145   23   19  82
B     67   18  138  116  139  78
C     26   45   36  104   42  85
D     64  107  119   24   11  97